### ISSUE TITLE
Invalid argument(s): Could not find an option named "package-default-analysis-options".

### ISSUE THREAD

**Issue by refi64** [dam0vm3nt/todo_ddc#5]
Well, this is freaking weird:

```
ryan@DevPC-LX ~/stuff/todo_ddc master $ bazel build default
..............
INFO: Found 1 target...
ERROR: /home/ryan/.cache/bazel/_bazel_ryan/3964bd745b00ca954e33bbf6c14e12de/external/logging/BUILD:8:1: Polymerizing ../logging/logging.js failed: polymerize failed: error executing command bazel-out/host/bin/external/polymerize_tool/polymerize -o /tmp/out bazel -s external/logging/lib/logging.dart -T bazel-out/local-fastbuild/bin/external/logging/logging_template.map -M ... (remaining 15 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 255.
Unhandled exception:
Invalid argument(s): Could not find an option named "package-default-analysis-options".
#0      ArgResults.[] (package:args/src/arg_results.dart:60)
#1      createContextBuilderOptions (package:analyzer/src/command_line/arguments.dart:99)
#2      AnalyzerOptions.AnalyzerOptions.fromArguments (package:dev_compiler/src/analyzer/context.dart:72)
#3      _buildOne (package:polymerize/polymerize.dart:227)
<asynchronous suspension>
#4      runInBazelMode (package:polymerize/polymerize.dart:1193)
<asynchronous suspension>
#5      main (package:polymerize/polymerize.dart:1127)
<asynchronous suspension>
#6      main (http://localhost:37146/polymerize.dart:3)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
Target //:default failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /media/ryan/stuff/todo_ddc/BUILD:5:1 Polymerizing ../logging/logging.js failed: polymerize failed: error executing command bazel-out/host/bin/external/polymerize_tool/polymerize -o /tmp/out bazel -s external/logging/lib/logging.dart -T bazel-out/local-fastbuild/bin/external/logging/logging_template.map -M ... (remaining 15 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 255.
INFO: Elapsed time: 69.072s, Critical Path: 0.90s
ryan@DevPC-LX ~/stuff/todo_ddc master $ 
```

**Comment by dam0vm3nt** [comment]
Ok, it's an issue with `dart v 1.23.0` they have introduced the `frontend` and changed something with the analyzer. We need to update `polymerize` too. 

A quick fix could be to force the analyzer dependency to version `0.30.alpha.1`.

**Comment by dam0vm3nt** [comment]
you can try with : 
 - pub global activate polymerize

to update `polymerize` and retry the build.

**Comment by refi64** [comment]
It works now! Thanks!
